# My News Service build pipeline

trigger: 
  - main
  - feature*

pool:
  name: WmDevOpsTutorialAgentsPool
  vmImage: Canonical:0001-com-ubuntu-confidential-vm-focal:20_04-lts-gen2:latest

steps:
- script: chmod u+x ./azurePipelines/buildScripts/*.sh
  displayName: "Grant shell execution permissions"

- script: ./azurePipelines/buildScripts/01.setJobInitialVariables.sh
  displayName: 'Set job variables'

- script: ./azurePipelines/buildScripts/02.prepareAgentMachine.sh
  displayName: 'Install buildah'

# Service Principal Credentials
- task: DownloadSecureFile@1
  name: CRCredentials
  displayName: 'Download CR credentials'
  inputs:
    secureFile: 'cr.credentials.secret.sh'

- script: ./azurePipelines/buildScripts/03.build.sh
  displayName: 'Build'
